### ISSUE TITLE
Update Chris and Albert

### ISSUE THREAD

**Issue by imsickofmaps** [scaleconf/scaleconf.github.com#120]
Waiting for more info still to add to:

Chris Oloff - Building stuff in software - Uber5
has a goal to write efficient and well-performing code for small and not-so-small-any-more challenges, since 1994, with existing or news teams. He gained experience in diverse industries like metals, money and energy, and is still learning daily. Chris holds an Honours Degree in Computer Science and Economics from the University of Mannheim, Germany.
Photos: https://www.dropbox.com/s/lpgpgm65ac030fk/chris_oloff.large.jpg?dl=0 and https://www.dropbox.com/s/u5qj818da45qq9v/chris_oloff.small.jpg?dl=0

Albert de Jongh - Software Architect - Visa
is a software architect at Visa, and has often found himself in war rooms about performance problems.  He has stared at way too many thread dumps, trying to make sense of things that just could not have happened.
Photos: https://www.dropbox.com/s/iovm6wzefan7hyf/albert_dejongh.large.jpg?dl=0 and https://www.dropbox.com/s/gbqyfkua4rxzjzk/albert_dejongh.small.jpg?dl=0

**Comment by MarijeP** [comment]
Albert de Jongh is a software architect at Visa, and has often found himself in war rooms about performance problems.  He has stared at way too many thread dumps, trying to make sense of things that just could not have happened.
