### ISSUE TITLE
Add Maggie bio

### ISSUE THREAD

**Issue by imsickofmaps** [scaleconf/scaleconf.github.com#126]
1.     Full name: Maggie Zhou
2.     Organisation: Etsy
3.     Job title: Software Engineer
4.     Bio (max 50 words): Maggie Zhou works on the Core Platform team
at Etsy where she builds infrastructure to manage scaling challenges
in data storage and the web stack. She reads books, rides bicycles,
and drinks too much coffee in Brooklyn NY.
5     Headshot photo: https://www.dropbox.com/s/4tqcoxf0y12r8mq/maggie_zhou.large.jpg?dl=0 & https://www.dropbox.com/s/wczqu5w4h83vgmn/maggie_zhou.small.jpg?dl=0

**Comment by MarijeP** [comment]
For the talk info, she's given https://gist.github.com/zmagg/e7307ea2adf6cd510e95. Is there a title?

Can I use this as the abstract?

> In this talk, we'll go over the pains and perils of sharding databases and how we solved some of the problems in Etsy's second take on sharding, what we call logical sharding.

**Comment by imsickofmaps** [comment]
Title: Sharding Take Two, the Logical Edition
