### ISSUE TITLE
Reflect 2015 is over on site

### ISSUE THREAD

**Issue by imsickofmaps** [scaleconf/scaleconf.github.com#153]

**Comment by MarijeP** [comment]
We should do this. Also, the vid's are available - what do I do? Upload them to Youtube? If so, can someone send me the username/pwd for the account?

**Comment by duncanphillips** [comment]
I think its just using your google login, so its probably in the drop down
of apps in gmail

**Comment by vhata** [comment]
I'll do the videos, no problem...

**Comment by MarijeP** [comment]
@vhata how is it going?

**Comment by vhata** [comment]
Why are we communicating on Github?

I'll finish them today.

**Comment by adrianmoisey** [comment]
May be http://scaleconf.org/videos/ should be updated too?
