### ISSUE TITLE
Update /schedule

### ISSUE THREAD

**Issue by MarijeP** [scaleconf/scaleconf.github.com#157]
Probs better to comment out the schedule so it can be easily updated when we have the next one.

ScaleConf is a single-track conference run over three days. Generally the conference starts at 9am, there are six 45-minute talks a day with plenty of breaks in-between.

I'm no good at writing this stuff. Perhaps @imsickofmaps or @vhata would like to give me a blurb? I'm sure we had one before, where is it?

**Comment by duncanphillips** [comment]
+1 to just hiding for now

**Comment by vhata** [comment]
Last year before we put it up, it read:

Conference Schedule

We're pleased to announce that the conference schedule is extended for 2015! This years conference will **run over three days**, with a more *business of scale* oriented day running first on the Wednesday. More details of the schedule for the first day will be released soon.

The Business of Scale day focuses on the issues leaders and their teams face when growing a technology-driven organisation. You'll get to hear from those who've faced the challenges of building engineering teams, growing healthy customer acquisition strategies, maintaining inspiring working environments, balancing customer demands and technical debt, dealing with exit opportunities and more.

The **tried and tested** formula will be repeated for the second two days, with a total of **12 x 45 minute talks** plus regular breaks to keep the legs from falling asleep and awesome lunches to feed the mind and body.

Finally, we will have a weekend of full- or half-day **workshops**.

There will be **three social events** starting with the Wednesday evening with a sponsored drinks event in the city. Then similar events on the Thursday and Friday nights. These are a chance to socialise and network with the speakers, organisers, and fellow conference attendees.

**Comment by vhata** [comment]
Let's leave the workshops bit out.
