### ISSUE TITLE
Update /purchase

### ISSUE THREAD

**Issue by MarijeP** [scaleconf/scaleconf.github.com#158]
> Conference

> Dates: March 4-6, 2015

> Where: Kirstenbosch Botanical Gardens

> What's included in your ticket:

> International speakers sharing unique experiences.
> African speakers sharing local perspectives and solutions.
> Lunch every day, and tea/coffee/refreshments throughout the event.
> Evening events to network and meet like-minded people.
> Tickets are now closed for 2015 and the waitlist is over-subscribed. Get in quick next year!

Change to:

> Conference

> Dates: 2016 dates to be confirmed

> Where: Kirstenbosch Botanical Gardens

> What's included in your ticket:

> International speakers sharing unique experiences.
> African speakers sharing local perspectives and solutions.
> Lunch every day, and tea/coffee/refreshments throughout the event.
> Evening events to network and meet like-minded people.

***

> Student and Discount tickets

> If you wish to motivate for a discount on your ticket, please drop us a mail at info@scaleconf.org.

> Payment Processor

> ScaleConf is using Quicket as our payment processor, and the organising beneficiary for ScaleConf is Lessfuss.

> If you have any problems at all with payment, please email info@scaleconf.org and we will assist you as soon as we can.

Change to:

> Student and Discount tickets

> If you wish to motivate for a discount on your ticket, please drop us a mail at info@scaleconf.org.

> Payment Processor

> ScaleConf uses Quicket as a payment processor, and the organising beneficiary for ScaleConf is Lessfuss.

**Comment by duncanphillips** [comment]
we should probably keep the text around where to contact us about ticket issues - even if thats just directing them to quicket
