### ISSUE TITLE
Update /sponsors

### ISSUE THREAD

**Issue by MarijeP** [scaleconf/scaleconf.github.com#159]
Do we want to have a list of all previous sponsors - like the speakers page?

If not, just update the page to:

> Without the support of our generous sponsors ScaleConf would be a vastly more expensive conference for our attendees.

> Information on sponsoring ScaleConf 2016 will be available on our site later this year. However, if you'd like to get more information on sponsoring, please get in touch at info@scaleconf.org.

**Comment by duncanphillips** [comment]
i vote on just having the text.

**Comment by vhata** [comment]
Yeah, past sponsors already got what they paid for, don't want to dilute future sponsorships.
