### ISSUE TITLE
Update /about

### ISSUE THREAD

**Issue by MarijeP** [scaleconf/scaleconf.github.com#160]
Update `we're bringing ScaleConf back for the fourth time in April 2015` to `we're bringing ScaleConf back for the fifth time in 2016`.

***

> Special thanks to:

> Website contributors:
> Shaun O'Connell - @ndorfin
> Russell Cloran - @rcloran
> Stefano Rivera - @stefanorivera
> Vanessa Berger - @van_berger
> Adrian Moisey - @adrianmoisey

Change to:

? Are we going to list everyone who's ever helped? Can we add the minions?

***

**Organisers**

* Marije to update her picture, it's about bladdie time.
* @duncanphillips @vhata @imsickofmaps @JennP - any changes you'd like to make?

**Comment by duncanphillips** [comment]
i think its nice to keep a list of all the people that have helped. definitely keen to add minions.

**Comment by vhata** [comment]
For sure add the minions, and let's keep a historical list of "conference friends" around, even if we change the main bit to "current organizers".

**Comment by MarijeP** [comment]
Previous minions:
Ben Meier
Siobhan O'Donovan
Calvin Brizzi
Julia Lang

Must I find their Twitters?

**Comment by adrianmoisey** [comment]
> Must I find their Twitters?
 
Yes please.

> Marije to update her picture, it's about bladdie time

Do you have a new picture?

**Comment by MarijeP** [comment]
Ben Meier - @benmeier_
Siobhan O'Donovan - @justshiv_
Calvin Brizzi - @calvinbrizzi
Julia Lang - I have to ask her.

I don't have a new picture yet.

**Comment by adrianmoisey** [comment]
Thanks

**Comment by MarijeP** [comment]
Julia - @julia_melody

**Comment by adrianmoisey** [comment]
I think it's done now. Should we close?

**Comment by vhata** [comment]
No new picture for Marije yet.

**Comment by adrianmoisey** [comment]
Duh, sorry.

**Comment by imsickofmaps** [comment]
@MarijeP poke for picture

**Comment by MarijeP** [comment]
Poke her with a stick. 

I need to get my hair styled, makeup done and personal shopper to find me an outfit. This is going to take some time.

**Comment by adrianmoisey** [comment]
> Poke her with a stick.

A selfie-stick?

**Comment by MarijeP** [comment]
Added one via https://github.com/scaleconf/scaleconf.github.com/issues/225.
