### ISSUE TITLE
Update /videos

### ISSUE THREAD

**Issue by MarijeP** [scaleconf/scaleconf.github.com#161]
> Now preparing for its fourth year, ScaleConf has been fortunate to have had some great speakers deliver awesome talks in the past. Below are our previous speakers, with their talk abstracts and videos, where available.

Change to:

> Now preparing for its fifth year, ScaleConf has been fortunate to have had some great speakers deliver awesome talks in the past. Below are our previous speakers, with their talk abstracts and videos, where available.

***

Categorise by year, like /speakers?

***

Add 2015 videos etc. https://www.youtube.com/user/scaleconf.

**Comment by duncanphillips** [comment]
sounds good. can organise speakers by year, but i'm not fussed if we don't

**Comment by vhata** [comment]
I'd actually quite like the whole site to be categorized by year, so people can go back and see previous year's schedules, videos, speakers, sponsors, etc.  But a first win would be to make this more organized, yes.

**Comment by vhata** [comment]
Okay so:

/videos is only updated after a conference, so it's always referring to previous conferences.  If we could organize it by year, that would be great.  Section per year, with a grid of videos, in reverse chronological order.  If you want to get fancy with a tab on the side to jump to a particular year, go wild.  Ooh and a text box that dynamically filters the view as you type search terms.  Really make it pop.

However, /speakers can be "please submit + past speakers" or "please submit + current speakers + past speakers" or just "past speakers".  So I think having /speakers/past with all past speakers organized in the same way as the videos (really make it pop though) would be good, and we can toggle "please submit" and "current speakers" as we get closer to the next conference.

Make sense?

**Comment by MarijeP** [comment]
Do we still want to do this? I can help, I just don't know what the code should look like. If someone wants to show me, I'll go ahead.

**Comment by MarijeP** [comment]
Closing because redesign.
