### ISSUE TITLE
Ice Cream sponsorship

### ISSUE THREAD

**Issue by MarijeP** [scaleconf/scaleconf.github.com#173]
We've got a tentative OK from Kirstenbosch to allow an ice cream vendor in the foyer/outside.

We need to do the following:

- [ ] define cost
- [ ] add it to the sponsor doc/website
- [ ] confirm when it will be available to attendees (during a certain break, all the time, in the afternoon?)
- [ ] book the ice cream people

**Comment by MarijeP** [comment]
So that didn't happen.

**Comment by adrianmoisey** [comment]
:ice_cream: :(
