### ISSUE TITLE
SSL via cloudflare

### ISSUE THREAD

**Issue by adrianmoisey** [scaleconf/scaleconf.github.com#182]
Purchasing tickets without that :lock: in the top left hand corner is awkward. Yes, yes, it's in an iframe and it's secure.
What about using Cloudflare for their free SSL service?

**Comment by adrianmoisey** [comment]
Thanks github! https://scaleconf.org/

**Comment by MarijeP** [comment]
Nah, we Cloudflared 😄

**Comment by adrianmoisey** [comment]
nice!
