### ISSUE TITLE
Sponsors not displaying

### ISSUE THREAD

**Issue by adrianmoisey** [scaleconf/scaleconf.github.com#194]
I see this on multiple devices.:
![screenshot from 2016-02-07 19 40 34](https://cloud.githubusercontent.com/assets/736329/12873933/c176ed48-cdd2-11e5-8891-ba5cc128b1e4.png)

I attempted to fix this in https://github.com/scaleconf/scaleconf.github.com/commit/625f6dc69ab7f3c6a8b05628662b01d56b4d308f, but it got reverted in https://github.com/scaleconf/scaleconf.github.com/commit/01e2259ad34de0cc27bbdd6f5dc25f52c0a8b4de

**Comment by MarijeP** [comment]
Can I fix it? Or are you wanting someone to comment on it?

**Comment by adrianmoisey** [comment]
You certainly can. I figured I'd raise an issue rather then trying to fix it, in case it get reverted again.
