### ISSUE TITLE
"Sold out" changes to the website

### ISSUE THREAD

**Issue by MarijeP** [scaleconf/scaleconf.github.com#207]
Not so many tickets left, when they are sold out, can we get ready to replace it with Sold Out information and a link to https://docs.google.com/forms/d/1WOB3UD0XMfljzwqoqvqIw36xnuDbPs0RcjZDG5_L_4o/viewform where they can submit details.

**Comment by adrianmoisey** [comment]
Fixed in https://github.com/scaleconf/scaleconf.github.com/pull/208
