### ISSUE TITLE
Update /index.html

### ISSUE THREAD

**Issue by MarijeP** [scaleconf/scaleconf.github.com#219]
Remove `March 10-11 2016 - `, add March 2017, dates to be confirmed.

Revert to "previous speakers": https://github.com/scaleconf/scaleconf.github.com/commit/abee5d0011a94b994b1bb2872774c8b4f2271404#diff-eacf331f0ffc35d4b482f1d15a887d3bL65

Revert to "watch past talks": https://github.com/scaleconf/scaleconf.github.com/commit/abee5d0011a94b994b1bb2872774c8b4f2271404#diff-eacf331f0ffc35d4b482f1d15a887d3bL80

Other things from the old page: https://github.com/scaleconf/scaleconf.github.com/commit/52254f4b2b50ec69806fce84de38c1dd6dc45172

Replace the quote with one of these? 

`shoutout to @scaleconf. amazing venue, great talks and speakers. if 🔍 for a conf to share your experience scaling check it out` 
https://twitter.com/dschenkelman/status/710218787249917953

`Ok, finally coming home. Cape Town was amazing. 4 hours in Istanbul was lovely. And @ScaleConf, you are my new favorite.`
https://twitter.com/tbmcmullen/status/709337016417255424

`Thank you, @scaleconf, for a wonderful experience. Speakers take note: you want to speak at this conference. #scaleconf is worth the flight!`
https://twitter.com/bridgetkromhout/status/708419728419631105

`Incredible two days @scaleconf. One of my favourite ideas was @mgorven's Canary Tests`
https://twitter.com/bsinkwa/status/708370357573574656

`Had a fantastic #scaleconf, insightful talks, great people, beautiful venue`
https://twitter.com/henkjbrt/status/708353784477523968

`First @ScaleConf was great! Seriously impressed with the caliber of the talks. Will be back for sure.`
https://twitter.com/jonocoetzee/status/708319732571705344
^ might look like a very old tweet with the "first".

Feel free to put others if you've seen them. Even though they're public, should we get the ok from the tweeters?

**Comment by MarijeP** [comment]
Oh, put back the box to get notified: https://github.com/scaleconf/scaleconf.github.com/commit/adc85b1f27f22565b73e38082bd7316aa2f90651.

**Comment by adrianmoisey** [comment]
Make a thing that displays a random quote on the front page?

**Comment by MarijeP** [comment]
Make a random quote generator that uses the names of past attendees, right?

**Comment by adrianmoisey** [comment]
Make a random quote generator that uses the names of organisers

**Comment by adrianmoisey** [comment]
"I really like this conference" - Jonathan Hitchcock

**Comment by MarijeP** [comment]
"I learned alot" - Jennifer Poole

**Comment by adrianmoisey** [comment]
![image](https://cloud.githubusercontent.com/assets/736329/13951000/ebeb8ef4-f036-11e5-8eed-2ded2616d8c2.png)

**Comment by adrianmoisey** [comment]
"Marketing!" - Michael Jones

**Comment by MarijeP** [comment]
Also, change the text that appears in https://github.com/scaleconf/scaleconf.github.com/blob/master/index.html#L10. That is just shocking.

**Comment by adrianmoisey** [comment]
Done I think?

**Comment by MarijeP** [comment]
Dankie.
