### ISSUE TITLE
Update /schedule

### ISSUE THREAD

**Issue by MarijeP** [scaleconf/scaleconf.github.com#222]
Previous version: https://github.com/scaleconf/scaleconf.github.com/commit/491c35839eef4df3666115903862279a837321b2.

A basic overview of the structure. Everyone ok with it or should it be changed?

**Comment by adrianmoisey** [comment]
I'll try make this work with a switch

**Comment by adrianmoisey** [comment]
This got disabled with https://github.com/scaleconf/scaleconf.github.com/pull/230
Good to close?

**Comment by MarijeP** [comment]
Yes, thanks.
