### ISSUE TITLE
Update /sponsors

### ISSUE THREAD

**Issue by MarijeP** [scaleconf/scaleconf.github.com#224]
We probably don't want to add info on sponsoring 2017 yet.

Might be better to add a "if you would like to be notified about 2017 sponsorship opportunities, ..." and then have a form to go into the 2017 spreadsheet.

Otherwise, replace

> SPONSORS FOR 2016

with

> A HUGE THANK YOU TO OUR SPONSORS FOR 2015

**Comment by adrianmoisey** [comment]
I'll try make this work with a switch
