### ISSUE TITLE
Put conference details (date, etc) on the Call for Papers page

### ISSUE THREAD

**Issue by vhata** [scaleconf/scaleconf.github.com#241]
We're sending people directly to http://scaleconf.org/submit-talk/ but the only place the date and location are is on the front page...

**Comment by duncanphillips** [comment]
its also on the sponsor prospectus and the submit-talk form, but ja, maybe we can add a footer

**Comment by duncanphillips** [comment]
actually thinking about it, we should make it quite a lot more prominent

**Comment by vhata** [comment]
@imsickofmaps @duncanphillips: the site is kind of grim right now.

* the front page is pretty drab - the previous site was much more compelling
* no consistent footer with our contacts, social media links, etc
* the "about" page is more of a "history" page and has no details (especially since that's where people go when they fail to find the date/venue on other pages)
* there's no obvious link to the front page (you have to click on the logo), which is the only place with all the information prominently presented
* the "speakers" page is basically blank because we have no 2017 speakers, and you have to click through to get previous speakers which is a shitty experience
* the "sponsors" page is blank as well, and has no link to our sponsorship prospectus - not very useful at all
* we now have the date on the submit-talk page, but only in one place, and small, and I'm still getting people telling me that they can't see it on mobile (although I can't reproduce)

**Comment by duncanphillips** [comment]
- front page - i'm going to look at putting some images up, and probably a venue section as well. any other suggestions? 
- i'll make the footer global
- i'll rename about to history
- i'll add a link to home page in the title menu
- i think the speakers page being empty is fine. i think landing on a previous years speakers page would be confusing. What do you think would work better?
- i can add the prospectus to the sponsor page, i just wasn't sure if we wanted this to be a public document. My assumption was that we wanted to engage sponsors directly and talk to them about the prospectus.
- i'll add the date/location in more places

**Comment by vhata** [comment]
* That sounds good for the front page.  The stuff from last year's front page was good.
* Do we still need the history page?  I don't think people really care about why we decided to run the conference now.  We should still have an about page, with full details, maybe a very very short history (i.e it's been running since 2012), and a list of organizers/helpers at the bottom.
* Maybe on the speakers page, something that says:  "we're still selecting speakers for this year.  If you'd like to speak, <a href>submit a talk</a>" and then "Feel free to browse the speakers from previous years below".
* Also, in the individual years speakers, it's pretty unwieldy to have to scroll through a single column of every speaker, including bio, abstract, everything.  I think a grid of speaker name/avatar/twitter/github and the talk title, linking to an individual speaker page, would be much easier - people will also want to link to individual speakers/talks, and they can't in this format.
* Let's just take the sponsors page down until we have some sponsors.

Thanks!

**Comment by duncanphillips** [comment]
I think we need the history page, its a good place for people to just get an idea of who we are and how long the conference has been running etc.

i dont think we should remove the sponsors page, even though its so small, it still gives the info potential sponsors need if they want to contact us

**Comment by duncanphillips** [comment]
I dont have any good ideas on how to do the speakers page. I do think it would be good to collapse, but what i want to avoid is having to make 'placeholder' pages in jekyll for every speaker, its a pain to manage and what i was originally trying to get away from. I might be able to make a dialog that works properly on mobile as well, but will have to play around a bit. We could also have a list of speakers on the speakers page which makes navigating to the right speaker easier
